### ISSUE TITLE
A little issue in nerfuncertainty/scripts/save_noisy_images.py about parser.

### ISSUE THREAD

**Issue by qiyun71** [AaltoML/uncertainty-nerf-gs#1]
Hello, thank you for your excellent work. 
I find an inconsistent parser issue between [save_noisy_images.py](https://github.com/AaltoML/uncertainty-nerf-gs/blob/main/nerfuncertainty/scripts/save_noisy_images.py#L99) and [README.md ](https://github.com/AaltoML/uncertainty-nerf-gs/tree/main?tab=readme-ov-file#1-experiments-on-irreducible-uncertainty-aleatoric-confounding-effects) (--input-folder --output-folder and --operation).
Maybe the code in save_noisy_images.py should be modifed to `--input_folder` `--output_folder` and `--operation` in line 99 to 101. And the [README.md ](https://github.com/AaltoML/uncertainty-nerf-gs/tree/main?tab=readme-ov-file#1-experiments-on-irreducible-uncertainty-aleatoric-confounding-effects) should be modified to `--input_folder` `--output_folder` synchronously.
And the save_noise_images in [README.md ](https://github.com/AaltoML/uncertainty-nerf-gs/tree/main?tab=readme-ov-file#1-experiments-on-irreducible-uncertainty-aleatoric-confounding-effects) should be modify to `save_noisy_images`

**Comment by trappmartin** [comment]
Could you open a PR for this?

**Comment by marcusklasson** [comment]
Just merged your PR, @qiyun71 .Thank you for the fix! 
Closing this issue.
